import { Injectable, inject } from "@angular/core";
import { HttpClient, HttpContext } from "@angular/common/http";
import { NavigationEnd, Router } from "@angular/router";
import { BACKGROUND_REQUEST } from "../core/request-activity";
import { Observable, tap, finalize } from "rxjs";
import { MonitoringService } from "./monitoring.service";
import { environment } from "../../environments/environment";

export interface LoginRequest {
  userName: string;
  password: string;
}

export interface LoginResponse {
  accessToken: string;
  expiresAtUtc: string;
  userName: string;
  displayName: string;
  roles: string[];
  permissions: { code: string; accessType: string }[];
  sessionId: string;
}

@Injectable({ providedIn: "root" })
export class AuthService {
  private readonly http = inject(HttpClient);
  private readonly baseUrl = environment.identityApiUrl;
  private readonly router = inject(Router);
  private readonly monitoring = inject(MonitoringService);
  private activityTimer: ReturnType<typeof setTimeout> | undefined;
  private lastReported = 0;
  private activityInFlight = false;
  private activityPending = false;
  private sessionCheckInFlight = false;
  private readonly idleMs = 5 * 60 * 1000;

  constructor() {
    // Scroll events can be generated by code; input events represent user intent.
    for (const eventName of ["click", "input", "change", "submit"]) {
      document.addEventListener(eventName, event => {
        if (event.isTrusted && (eventName !== "click" || (event.target as Element)?.closest?.("button, a, input, select, textarea, [role=button]"))) this.recordActivity();
      }, { passive: true, capture: true });
    }
    let initialNavigation = true;
    this.router.events.subscribe(event => {
      if (!(event instanceof NavigationEnd)) return;
      if (!initialNavigation && event.urlAfterRedirects !== "/login") this.recordActivity();
      initialNavigation = false;
      if (this.getAccessToken()) void this.monitoring.openPage(event.urlAfterRedirects);
    });
    window.addEventListener("storage", event => {
      if (event.key === "access_token" && !event.newValue) this.clearSession();
    });
    setInterval(() => this.checkIdle(), 1000);
    // Hub disconnect/reconnect checks and API 401s detect revocation without polling.
    this.monitoring.disconnected.subscribe(() => this.checkServerSession());
    // Defer until DI has finished creating this service/interceptor.
    queueMicrotask(() => this.checkServerSession());
  }

  recordActivity(): void {
    if (!this.getAccessToken() || this.checkIdle()) return;
    localStorage.setItem("last_activity_at", String(Date.now()));
    this.activityPending = true;
    this.scheduleActivity();
  }

  private scheduleActivity(): void {
    if (this.activityInFlight || !this.activityPending) return;
    // Leading/trailing coalescing retains the final event without scroll floods.
    if (Date.now() - this.lastReported >= 60000) this.reportActivity();
    else if (!this.activityTimer) this.activityTimer = setTimeout(() => {
      this.activityTimer = undefined;
      this.reportActivity();
    }, Math.max(0, 60000 - (Date.now() - this.lastReported)));
  }

  private reportActivity(): void {
    if (this.activityInFlight || !this.activityPending || !this.getAccessToken() || this.checkIdle()) return;
    if (this.activityTimer) clearTimeout(this.activityTimer);
    this.activityTimer = undefined;
    this.activityPending = false;
    this.activityInFlight = true;
    this.lastReported = Date.now();
    this.http.post<void>(`${this.baseUrl}/auth/activity`, {}, {
      headers: { "X-User-Activity": "1", "X-Activity-Age-Ms": String(Math.min(60000, Math.max(0, Date.now() - Number(localStorage.getItem("last_activity_at"))))) },
      context: new HttpContext().set(BACKGROUND_REQUEST, true),
    }).pipe(finalize(() => {
      this.activityInFlight = false;
      this.scheduleActivity();
    })).subscribe({ error: () => { /* 401 handled centrally; never retry activity. */ } });
  }

  private checkServerSession(): void {
    if (document.hidden || this.sessionCheckInFlight || !this.getAccessToken() || this.checkIdle()) return;
    this.sessionCheckInFlight = true;
    this.http.get(`${this.baseUrl}/auth/session`, {
      context: new HttpContext().set(BACKGROUND_REQUEST, true),
    }).pipe(finalize(() => this.sessionCheckInFlight = false)).subscribe({ error: () => { /* Failures never renew activity. */ } });
  }

  private checkIdle(): boolean {
    if (!this.getAccessToken()) return false;
    const last = Number(localStorage.getItem("last_activity_at"));
    const expires = this.getExpiresAt();
    if (!last || Date.now() - last >= this.idleMs || (expires && Date.parse(expires) <= Date.now())) {
      this.clearSession();
      return true;
    }
    return false;
  }

  markRequestActivity(): void { this.checkIdle(); }

  login(request: LoginRequest): Observable<LoginResponse> {
    return this.http
      .post<LoginResponse>(`${this.baseUrl}/auth/login`, request)
      .pipe(
        tap((response) => {
          localStorage.setItem("access_token", response.accessToken);
          localStorage.setItem(
            "permissions",
            JSON.stringify(response.permissions ?? []),
          );
          localStorage.setItem("user_name", response.userName);
          localStorage.setItem("display_name", response.displayName);
          localStorage.setItem("roles", JSON.stringify(response.roles ?? []));
          localStorage.setItem("session_id", String(response.sessionId));
          localStorage.setItem("expires_at_utc", response.expiresAtUtc);
          localStorage.setItem("last_activity_at", String(Date.now()));
        }),
      );
  }

  logout(): void {
    if (this.getAccessToken()) this.http.post<void>(`${this.baseUrl}/auth/logout`, {}, {
      context: new HttpContext().set(BACKGROUND_REQUEST, true),
    }).subscribe({ error: () => { /* Offline sessions still expire on the server. */ } });
    this.clearSession();
  }

  clearSession(): void {
    if (this.activityTimer) clearTimeout(this.activityTimer);
    this.activityTimer = undefined;
    this.activityPending = false;
    void this.monitoring.disconnect().catch(() => {});
    localStorage.removeItem("access_token");
    localStorage.removeItem("permissions");
    localStorage.removeItem("user_name");
    localStorage.removeItem("display_name");
    localStorage.removeItem("roles");
    localStorage.removeItem("session_id");
    localStorage.removeItem("expires_at_utc");
    localStorage.removeItem("last_activity_at");
    void this.router.navigateByUrl("/login");
  }

  getAccessToken(): string | null {
    return localStorage.getItem("access_token");
  }

  isAuthenticated(): boolean {
    return !!this.getAccessToken();
  }

  hasPermission(permission: string): boolean {
    return this.hasAccess(permission, "VIEW");
  }

  hasAccess(permission: string, accessType: string): boolean {
    return this.getPermissions().some(x => x.code === permission && x.accessType === accessType);
  }

  getPermissions(): { code: string; accessType: string }[] {
    const value = localStorage.getItem("permissions");
    if (!value) return [];
    try {
      const parsed = JSON.parse(value);
      return Array.isArray(parsed) ? parsed : [];
    } catch {
      return [];
    }
  }

  getUserName(): string { return localStorage.getItem("user_name") || this.tokenClaims()?.["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"] || "—"; }
  getDisplayName(): string { return localStorage.getItem("display_name") || this.tokenClaims()?.["display_name"] || this.getUserName(); }
  getSessionId(): string { return localStorage.getItem("session_id") || String(this.tokenClaims()?.["session_id"] ?? "—"); }
  getExpiresAt(): string | null {
    const stored = localStorage.getItem("expires_at_utc");
    if (stored) return stored;
    const expiry = Number(this.tokenClaims()?.["exp"]);
    return Number.isFinite(expiry) && expiry > 0 ? new Date(expiry * 1000).toISOString() : null;
  }
  getRoles(): string[] {
    try {
      const parsed = JSON.parse(localStorage.getItem("roles") || "[]");
      if (Array.isArray(parsed) && parsed.length) return parsed;
    } catch { /* Use the current token for sessions created before this UI update. */ }
    const role = this.tokenClaims()?.["http://schemas.microsoft.com/ws/2008/06/identity/claims/role"];
    return Array.isArray(role) ? role : role ? [String(role)] : [];
  }

  private tokenClaims(): Record<string, any> | null {
    const token = this.getAccessToken();
    if (!token) return null;
    try {
      const payload = token.split(".")[1].replace(/-/g, "+").replace(/_/g, "/");
      return JSON.parse(decodeURIComponent(Array.from(atob(payload.padEnd(Math.ceil(payload.length / 4) * 4, "="))).map((character) => `%${character.charCodeAt(0).toString(16).padStart(2, "0")}`).join("")));
    } catch { return null; }
  }
}
